version: '3.1'

services:
  
  db:
    image: mysql:lts
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: pabloh
      MYSQL_PASSWORD: 
      MYSQL_DATABASE: gvendas_db
      MYSQL_ROOT_PASSWORD: 
